### ISSUE TITLE
Removing and adding controls to a container won't display them

### ISSUE THREAD

**Issue by Wh1teDuke** [simonkrauter/NiGui#123]
Sorry to bother you again, but I run into a different issue:
```nim
import nigui

proc test =
  app.init()

  var window = newWindow()
  var container = newLayoutContainer(Layout_Vertical)

  window.add(container)
  container.add(newLabel("Label"))

  discard startRepeatingTimer(1000, proc(event: TimerEvent) =
    var controls = container.childControls()
    for c in controls: container.remove(c)
    controls.add(newLabel("Label"))
    for c in controls: container.add(c)
  )

  window.show()
  app.run()

test()
```
Once the timer kicks in, no label will appear on screen, don't know if I'm doing something wrong. This is what the terminal displays:
`(test:3376): Gtk-CRITICAL **: gtk_widget_create_pango_layout: assertion 'GTK_IS_WIDGET (widget)' failed`
`(test:3376): Pango-CRITICAL **: pango_layout_get_extents_internal: assertion 'layout != NULL' failed`

**Comment by Sznymo** [comment]
I join the question
