### ISSUE TITLE
Make window not resizable

### ISSUE THREAD

**Issue by kzerot** [simonkrauter/NiGui#125]
Hi! 
Sometimes  you need make not resizable window. 
So far I haven't found such feature in NiGui, am I wrong?

**Comment by TheFourchette** [comment]
I saw in the code that there were an event that is triggered when the window get resized, so you could use that to detect when the window get resized and resize it back

**Comment by TheFourchette** [comment]
Something like this should work

```nim
window.handleResizeEvent = proc(event: ResizeEvent) = 
    window.width = 600.scaleToDpi
    window.height = 400.scaleToDpi
```
