### ISSUE TITLE
Deprecation warnings while building on Linux

### ISSUE THREAD

**Issue by felixp7** [simonkrauter/NiGui#168]
Like the title says, I get a number of deprecation warnings while building an app that uses NiGui:

```
/home/felix/Projects/web/ludimania/misc/turtle/lib/nigui.nim(2686, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
......
/home/felix/Projects/web/ludimania/misc/turtle/lib/nigui/private/gtk3/platform_impl.nim(423, 51) Warning: implicit conversion to 'cstring' from a non-const location: dialog.title; this will become a compile time error in the future [CStringConv]
```

followed by 9 more like the last one. This happens with a snapshot of NiGui from here as of the last commit, and also with a version from two years ago. This is with Nim 1.6.10 installed from the official binaries. My app (including NiGui) builds and runs fine otherwise.

I'm on a 64-bit machine with Debian 10 and GCC 8.3.0, for what it's worth.

**Comment by simonkrauter** [comment]
Thanks for reporting. Maybe I will wait for the release of Nim 2.0 to fix all warnings together.

**Comment by simonkrauter** [comment]
All warnings should be gone now (under Linux), except for one warning about lock levels (which I don't understand and will be removed in Nim 2.0).

**Comment by felixp7** [comment]
Confirmed. Thank you very much!
