### ISSUE TITLE
Right click on button

### ISSUE THREAD

**Issue by Kaz-Kawashima** [simonkrauter/NiGui#180]
Thank you for providing such a wonderful library.

Can I add right click event on button?

I'm making mine sweeper for my hoby, and I'd like to add "Flag" function to right click.
![image](https://github.com/simonkrauter/NiGui/assets/150841863/f2a8d3c5-5288-4c6b-91c6-1fb28fa8add7)

**Comment by simonkrauter** [comment]
I think this should work like this:
```nim
button.onMouseButtonDown = proc (event: MouseEvent) =
  if event.button == MouseButton_Right:
    echo "right click"
```

**Comment by Kaz-Kawashima** [comment]
Thank you for quick reply!

I could implement it!
![image](https://github.com/simonkrauter/NiGui/assets/150841863/625ed4a9-30ba-4bb7-8547-17fea98053f9)
