### ISSUE TITLE
resizable text area?

### ISSUE THREAD

**Issue by Douper2** [simonkrauter/NiGui#188]
im currently working on an ide for old windows versions and i was wondering if i could resize the text area to make space for the selected folder and the files inside it.

**Comment by simonkrauter** [comment]
Yes, the size of the text area widget can be set by code or by the parent container.
By default the text area use all available space.

**Comment by Douper2** [comment]
> Yes, the size of the text area widget can be set by code or by the parent container. By default the text area use all available space.

and how can i do that?

**Comment by simonkrauter** [comment]
```nim
textarea.width = ...
textarea.height = ...
```

**Comment by Douper2** [comment]
> ```nim
> textarea.width = ...
> textarea.height = ...
> ```

thank you so much
