### ISSUE TITLE
Why is "fOnMouseMove: MouseMoveProc" commented out?

### ISSUE THREAD

**Issue by nnahito** [simonkrauter/NiGui#94]
I want to detect mouse movement.
Therefore, I would like to use the function of `fOnMouseMove: MouseMoveProc`, but it was commented out when I saw the code.

https://github.com/trustable-code/NiGui/blob/master/src/nigui.nim#L279

---

Can't I use this?

Thank you

**Comment by arkocal** [comment]
I would also be interested in this. I see the bindings are not implemented, but I do not see why that would be more complicated than doing so for the similar press or release events. 

@trustable-code Is this a left out WIP or were there unexpected problems? I would be interested in implementing it.

**Comment by PMunch** [comment]
I am also in need of a mouse move callback for a custom widget, in order to allow drag and drop of items in the widget.

**Comment by simonkrauter** [comment]
I have implemented it now, see 4c0ae23.
You need to use the git head revision.
Feedback is welcome, especially how it affects the application's CPU usage under Windows.

**Comment by PMunch** [comment]
Oh cool! Unfortunately I don't even remember what I was trying to do, so I can't easily test it out
